const sampleProducts = [
  {
    name: "BassBlitz Bluetooth Speaker",
    price: 79.99,
    categories: ["Audio", "Accessories"],
    productImages: ["img/bassblitz.jpg"],
    averageRating: 4.7,
    discount: 15,
    description:
      "Portable Bluetooth speaker with deep bass and water resistance.",
    stock_quantity: 120,
    brand: "BeatBoom",
  },
  {
    name: "GlowFit Smart Band",
    price: 49.99,
    categories: ["Electronics", "Accessories"],
    productImages: ["img/glowfit.jpg"],
    averageRating: 4.4,
    discount: 5,
    description: "Compact smart band with activity tracking and OLED display.",
    stock_quantity: 200,
    brand: "FitNova",
  },
  {
    name: "ArcticFlex Winter Jacket",
    price: 89.99,
    categories: ["Clothing"],
    productImages: ["img/arcticflex.jpg"],
    averageRating: 4.5,
    discount: 10,
    description:
      "Waterproof winter jacket with thermal insulation and zip pockets.",
    stock_quantity: 75,
    brand: "FrostWear",
  },
  {
    name: "PulseWave Neckband",
    price: 39.99,
    categories: ["Audio", "Accessories"],
    productImages: ["img/pulsewave.jpg"],
    averageRating: 4.2,
    discount: 7,
    description:
      "Sleek wireless neckband with vibration alert and fast charging.",
    stock_quantity: 180,
    brand: "SoundGenix",
  },
  {
    name: "PixelPro Action Cam",
    price: 199.99,
    categories: ["Electronics"],
    productImages: ["img/pixelpro.jpg"],
    averageRating: 4.6,
    discount: 30,
    description:
      "Compact 4K action camera with wide-angle lens and stabilization.",
    stock_quantity: 60,
    brand: "SnapGear",
  },
  {
    name: "UrbanBeats Hoodie",
    price: 54.99,
    categories: ["Clothing"],
    productImages: ["img/urbanbeats.jpg"],
    averageRating: 4.3,
    discount: 6,
    description: "Trendy hoodie with kangaroo pockets and soft brushed cotton.",
    stock_quantity: 140,
    brand: "UrbanEdge",
  },
  {
    name: "CoreSound Studio Mic",
    price: 109.99,
    categories: ["Audio"],
    productImages: ["img/coresound.jpg"],
    averageRating: 4.8,
    discount: 20,
    description:
      "Professional-grade condenser mic for recording and voiceovers.",
    stock_quantity: 40,
    brand: "VibeAudio",
  },
  {
    name: "ChargeMate Cable Pack",
    price: 24.99,
    categories: ["Accessories"],
    productImages: ["img/chargemate.jpg"],
    averageRating: 4.1,
    discount: 4,
    description: "Set of 3 fast-charging USB-C and Lightning cables.",
    stock_quantity: 300,
    brand: "PlugSmart",
  },
  {
    name: "StyleFlex Joggers",
    price: 44.99,
    categories: ["Clothing"],
    productImages: ["img/styleflex.jpg"],
    averageRating: 4.0,
    discount: 5,
    description: "Breathable joggers with elastic waistband and modern fit.",
    stock_quantity: 160,
    brand: "FlexiWear",
  },
  {
    name: "ZenPods Max",
    price: 149.99,
    categories: ["Audio", "Accessories"],
    productImages: ["img/zenpods.jpg"],
    averageRating: 4.9,
    discount: 25,
    description:
      "Premium ANC earbuds with wireless charging and touch control.",
    stock_quantity: 90,
    brand: "ZenSound",
  },
];
